name: Lint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container-image }}
    strategy:
      matrix:
        container-image: ["rockylinux:8", "rockylinux:9"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Python
      run: |
        dnf install -y python3 findutils
    - name: Install dependencies
      run: |
        python3 -m venv "$RUNNER_TEMP/venv"
        "$RUNNER_TEMP/venv/bin/pip" install --upgrade pip
        "$RUNNER_TEMP/venv/bin/pip" install -r requirements.txt
        "$RUNNER_TEMP/venv/bin/pip" install -r test_requirements.txt
    - name: Analysing any changed code with pylint
      run: |
        find . -type f -name '*.py' | xargs -r "$RUNNER_TEMP/venv/bin/pylint" --max-line-length=120
