name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container-image }}
    strategy:
      matrix:
        container-image: ["rockylinux:8", "rockylinux:9"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Python
      run: |
        dnf install -y python3 python3-pip
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -r test_requirements.txt
    - name: Running unit tests with pytest
      run: |
        cd aquilon/ && pytest -vv
