name: Unit Tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container-image }}
    strategy:
      matrix:
        container-image: ["rockylinux:8", "rockylinux:9"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Python
      run: |
        dnf install -y python3
    - name: Install dependencies
      run: |
        python3 -m venv "$RUNNER_TEMP/venv"
        "$RUNNER_TEMP/venv/bin/pip" install --upgrade pip
        "$RUNNER_TEMP/venv/bin/pip" install -r requirements.txt
        "$RUNNER_TEMP/venv/bin/pip" install -r test_requirements.txt
    - name: Running unit tests with pytest
      run: |
        cd aquilon/ && "$RUNNER_TEMP/venv/bin/pytest" -vv
